ALTER TABLE "CONFIG_SITE" RENAME TO "_CONFIG_SITE_old_20260804_";

CREATE TABLE "CONFIG_SITE" (
  "ID" INTEGER NOT NULL,
  "NAME" TEXT,
  "PRI" INTEGER,
  "RSSURL" TEXT,
  "SIGNURL" TEXT,
  "COOKIE" TEXT,
  "INCLUDE" TEXT,
  "NOTE" TEXT,
  "TOKEN" TEXT,
  "API_KEY" TEXT,
  PRIMARY KEY ("ID")
);

INSERT INTO "CONFIG_SITE" ("ID", "NAME", "PRI", "RSSURL", "SIGNURL", "COOKIE", "INCLUDE", "NOTE", "TOKEN", "API_KEY") 
SELECT "ID", "NAME", "PRI", "RSSURL", "SIGNURL", "COOKIE", "INCLUDE", "NOTE", "TOKEN", "API_KEY" FROM "_CONFIG_SITE_old_20260804_";

DROP TABLE IF EXISTS "_CONFIG_SITE_old_20260804_";

ALTER TABLE "CONFIG_FILTER_RULES" RENAME TO "_CONFIG_FILTER_RULES_old_20260804";

CREATE TABLE "CONFIG_FILTER_RULES" (
  "ID" INTEGER NOT NULL,
  "GROUP_ID" TEXT,
  "ROLE_NAME" TEXT,
  "PRIORITY" INTEGER,
  "INCLUDE" TEXT,
  "EXCLUDE" TEXT,
  "SIZE_LIMIT" TEXT,
  "NOTE" TEXT,
  PRIMARY KEY ("ID")
);

INSERT INTO "CONFIG_FILTER_RULES" ("ID", "GROUP_ID", "ROLE_NAME", "PRIORITY", "INCLUDE", "EXCLUDE", "SIZE_LIMIT", "NOTE") 
SELECT "ID", "GROUP_ID", "ROLE_NAME", "PRIORITY", "INCLUDE", "EXCLUDE", "SIZE_LIMIT", "NOTE" FROM "_CONFIG_FILTER_RULES_old_20260804";

DROP TABLE IF EXISTS "_CONFIG_FILTER_RULES_old_20260804";
