ALTER TABLE CONFIG_SITE ADD COLUMN TOKEN TEXT;
ALTER TABLE CONFIG_SITE ADD COLUMN API_KEY TEXT;
UPDATE INDEXER_SITE SET RENDER = 1, PARSER='' where PARSER = 'RenderSpider';
UPDATE INDEXER_SITE SET PARSER = 'MTorrentSpider' where ID = 'mteam';
