ALTER TABLE INDEXER_SITE ADD COLUMN EN_EXPAND BOOLEAN;
UPDATE INDEXER_SITE SET SEARCH_TYPE = 'title' where SEARCH_TYPE = 'title,en_name';
UPDATE INDEXER_SITE SET EN_EXPAND = 0 where EN_EXPAND is NULL;