name: NAStool Docker Dev
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - version.py
      - .github/workflows/build-dev.yml
      - package_list.txt
      - requirements.txt
      - docker/dev.Dockerfile
      - app/*
      - web/*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Release version
        id: release_version
        run: |
          app_version=$(cat version.py |sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
          echo "app_version=$app_version" >> $GITHUB_ENV

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Date for Docker Tag
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/dev.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:dev
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:dev-${{ steps.get-date.outputs.date }}